// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGrJOl73OG6Lj3OpvaKPNaf6NoGZgZ9Zs',
    appId: '1:686337904007:web:259ba5ae77a04f97419722',
    messagingSenderId: '686337904007',
    projectId: 'my-subscriptions-c47d7',
    authDomain: 'my-subscriptions-c47d7.firebaseapp.com',
    storageBucket: 'my-subscriptions-c47d7.firebasestorage.app',
    measurementId: 'G-FXHN0HX3HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkYQ2PoDWqf11cizqm01R5n89koeze8oQ',
    appId: '1:686337904007:android:e7aba2481a394c42419722',
    messagingSenderId: '686337904007',
    projectId: 'my-subscriptions-c47d7',
    storageBucket: 'my-subscriptions-c47d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5vRE-9803ugsuuVSyKT-y5qQTVh2Fv0',
    appId: '1:686337904007:ios:317d1d9290e00a1a419722',
    messagingSenderId: '686337904007',
    projectId: 'my-subscriptions-c47d7',
    storageBucket: 'my-subscriptions-c47d7.firebasestorage.app',
    iosBundleId: 'com.example.mySubscriptions',
  );
}
